### ISSUE TITLE
Weird hole sizes in plate(?)

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-mu#17]
I'm guessing that the 3,9 mm holes in the top plate are for mounting different components.
What mounting method(s) are you planning to use?

If using bolts, then 3 mm diameter holes for M3 bolts should be enough.

![pilt](https://user-images.githubusercontent.com/32770145/205363095-be4a302b-b945-479a-8b39-7c25277be62e.png)

**Comment by CanOfIdeas** [comment]
The 3.9mm holes are for threaded inserts
