### ISSUE TITLE
Camera mount not attached to plate

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-mu#18]
The camera mount is not attached to the plate.
Add holes for bolts to attach it.

![pilt](https://user-images.githubusercontent.com/32770145/205363824-49cdc574-113e-419b-b21f-61fb1391e55d.png)

**Comment by CanOfIdeas** [comment]
Fixed it

**Comment by Akustav** [comment]
Hole sizes are somewhat iffy but will take care so they are correct in the CAM
