### ISSUE TITLE
Spacers holding the guards

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-mu#19]
The inner hole is 3,9 mm and distance between outside faces is 4,5 mm.
Are these the actual dimensions of the spacers you plan to use?

![pilt](https://user-images.githubusercontent.com/32770145/205364400-d00585e7-e6b7-452c-a331-3b7caa94b9c6.png)

**Comment by CanOfIdeas** [comment]
Just messed up the dimension a tad, should be 5.5, not 4.5. I'll be using the spacers provided in the lab. The width of the spacers should not be important in the grand scheme of thing though...
