### ISSUE TITLE
Camera mount spacers

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-mu#20]
The inner diameter for the camera mount spacers is 3,2 mm and distance between outside faces is 4,5 mm.
What spacers are you planning to use here?

You could use M3 spacers here. The holes in the camera mount sides should be 3 mm as well then.

**Comment by CanOfIdeas** [comment]
3.2 mm holes is an old habit from 3D printing, a sliding fit for M3 bolts. I will be using the M3 spacers in stock. Fixed the hole sizes.
