### ISSUE TITLE
What attachment method is used to attach the battery holders to the chassis

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-mu#25]
Title explains it. Both holes are 3.90 mm in diameter.

![image](https://user-images.githubusercontent.com/5435954/205368334-c3bc2bf4-983c-4ea9-b580-08b19feff1c3.png)

**Comment by CanOfIdeas** [comment]
3.9mm is the size I need for the threaded inserts. In the current design the insert is in the 3D printed piece, and the battery holder is then bolted to the chassis from the other side. The 3.9 mm hole in the chassis is a mix of laziness and laziness. On the one hand it was easier to design on the other I don't want to drill the hole larger, should I in the future decide to put the insert into the chassis. I am not attached to the 3.9mm hole in the chassis, I can change it, if you want.
