### ISSUE TITLE
0 centering for the thrower

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-mu#28]
There is literally 0 centering aid for the thrower. This puts a huge strain on the code to perfectly approach the ball every time.

![image](https://user-images.githubusercontent.com/5435954/205369372-ab94bb31-bea6-4d30-b4bb-b131f4ab7b49.png)

**Comment by CanOfIdeas** [comment]
Will do, but it's not currently part of the minimum viable product. Those 3 holes in front are for that exact purpose
